id: P008147
initial_creation_type: ocr
source_metadata:
  id: bdr:W29208
  title: གསེར་ཀོང་རྡོ་རྗེ་འཆང་ཆེན་པོའི་རྣམ་ཐར་སྐལ་བཟང་རེ་སྐོང
  author: ''
  volumes:
    86cc3a3609294e87a705c51fc711fce7:
      image_group_id: I1GS105484
      title: ''
      volume_number: 1
      total_pages: 324
ebook_metadata:
  title: གསེར་ཀོང་རྡོ་རྗེ་འཆང་ཆེན་པོའི་རྣམ་ཐར་སྐལ་བཟང་རེ་སྐོང
  author: ''
  sku: P008147
  cover: cover.jpg
  layers:
  - pagination
