id: I2CB48E46
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T07:18:59+00:00'
last_modified: '2022-06-09T04:49:53.064281+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29208
  title: གསེར་ཀོང་རྡོ་རྗེ་འཆང་ཆེན་པོའི་རྣམ་ཐར་སྐལ་བཟང་རེ་སྐོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4DA0:
      image_group_id: I1GS105484
      title: Volume 1 of gser kong rdo rje 'chang chen po'i rnam thar skal bzang re
        skong
      total_pages: 324
      order: 1
      base_file: 4DA0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
